name: AutoCommand

on:
  issues:
    types: [ opened, edited ]
  repository_dispatch:
    types: [ force_check ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # $GITHUB_WORKSPACE
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2
    
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Python Dependency
      run: |
        pip install -r ./Tools/Lambda/requirements.txt
    
    - name: Check Issues
      run: |
        cd $GITHUB_WORKSPACE
        python ./Tools/Lambda/GithubIssues.py
    
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}