name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # $GITHUB_WORKSPACE
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2
    
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
  
    - name: Python Dependency
      run: |
        pip install -r ./Tools/requirements.txt

    - name: Build Dict
      run: |
        cd $GITHUB_WORKSPACE
        python ./Tools/GithubBuild.py

    - name: Re-check Issues
      run: |
        cd $GITHUB_WORKSPACE
        python ./Tools/GithubIssues.py
    
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}